# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2.0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0.0", :group => [:development, :test]
gem "hoe-git", "~>1.5.0", :group => [:development, :test]
gem "rspec", "~>2.11.0", :group => [:development, :test]
gem "autotest-standalone", "~>4.5.0", :group => [:development, :test]
gem "rspec-given", "~>1.0", :group => [:development, :test]
gem "simplecov", "~>0.6.0", :group => [:development, :test]
gem "em-proxy", "~>0.1.0", :group => [:development, :test]
gem "ci_reporter", "~>1.7.0", :group => [:development, :test]
gem "activesupport", ">=2.3.0", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

# vim: syntax=ruby
